Models/Ilan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public int IlanId { get; set; }
        public string IlanBasligi { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public bool AnasayfadaGoster { get; set; }
        public bool Published { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid IlanSahibi { get; set; }
        public decimal Fiyati { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string IlanResimleri { get; set; }
        public string Video { get; set; }
        public string PostaKodu { get; set; }
        public System.DateTime IlanTarihi { get; set; }
        public int GoruntulenmeSayisi { get; set; }
        public int AltKategoriId { get; set; }
    }
}

Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using moto.Models;
using moto.App_Start;
namespace moto.Controllers
{
    public class IlanController : Controller
    {
        private motobulvarEntities db = new motobulvarEntities();

        // GET: Ilan
        public ActionResult Index()
        {
            return View(db.Ilan.ToList());
        }

        // GET: Ilan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilan.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // GET: Ilan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ilan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IlanId,IlanBasligi,ShortDescription,FullDescription,AnasayfadaGoster,Published,Active,Deleted,CreatedOn,UpdatedOn,IlanSahibi,Fiyati,Lat,Lon,IlanResimleri,Video,PostaKodu,IlanTarihi,GoruntulenmeSayisi,AltKategoriId")] Ilan ilan)
        {
            if (ModelState.IsValid)
            {
                db.Ilan.Add(ilan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ilan);
        }

        // GET: Ilan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilan.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // POST: Ilan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IlanId,IlanBasligi,ShortDescription,FullDescription,AnasayfadaGoster,Published,Active,Deleted,CreatedOn,UpdatedOn,IlanSahibi,Fiyati,Lat,Lon,IlanResimleri,Video,PostaKodu,IlanTarihi,GoruntulenmeSayisi,AltKategoriId")] Ilan ilan, string PostaKoduId)
        {
            if (ModelState.IsValid)
            {
                ilan.PostaKodu = PostaKoduId;
                ilan.AnasayfadaGoster = false;
                ilan.Published = false;
                ilan.Active = false;
                ilan.Deleted = false;
                ilan.CreatedOn = DateTime.Now;
                ilan.UpdatedOn = DateTime.Now;
                ilan.IlanSahibi = Guid.Parse("05d9de39-b810-49ee-a245-befa07f4c4de");
                ilan.IlanTarihi = DateTime.Today;
                db.Entry(ilan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ilan);
        }

        // GET: Ilan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilan.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // POST: Ilan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ilan ilan = db.Ilan.Find(id);
            db.Ilan.Remove(ilan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult MyPartialView()
        {
            return PartialView("MyPartialView");
        }


        public ActionResult motoE(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //mot_Motor mot_Motor = db.mot_Motor.Find(id);
            //if (mot_Motor == null)
            //{
            //    return HttpNotFound();
            //}
            ViewBag.index = 0;
            ViewBag.IlanId = id;
            Query q = new Query();
            ViewBag.MotosikletId = q.IlanIddenMotosikletIdDon(id);
            return View();
        }

    }
}

Views/Ilan/Create.cshtml
@model moto.Models.Ilan

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ilan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IlanBasligi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanBasligi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanBasligi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnasayfadaGoster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AnasayfadaGoster)
                    @Html.ValidationMessageFor(model => model.AnasayfadaGoster, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Deleted)
                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IlanSahibi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanSahibi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanSahibi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IlanResimleri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanResimleri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanResimleri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostaKodu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostaKodu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostaKodu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IlanTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoruntulenmeSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GoruntulenmeSayisi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoruntulenmeSayisi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AltKategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AltKategoriId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AltKategoriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ilan/Edit.cshtml
@model moto.Models.Ilan

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ilan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IlanId)
        
        
        
        <h4>Kategori Bilgisi</h4>
        <hr />

        <table class="table-responsive" style="background-color:gainsboro;width: 100%;border:inset;">
            <tr>
                @*<td >
                    @Html.LabelFor(model => model.PostaKodu, "Adres Bilgisi", htmlAttributes: new { @class = "control-label col-md-0" })
                </td>*@
                <td>
                    @Html.Action("Index", "KategoriAltKategori", new { IlanId = Model.IlanId })
                </td>
            </tr>
        </table>
        <br /><br />
        
        <h4>Konum Bilgisi</h4>
        <hr />

        <table class="table-responsive" style="background-color:gainsboro;width: 100%;border:inset;">
            <tr>
                <td>
                    @Html.Action("Index", "IlIlce", new { IlanId = Model.IlanId })
                </td>
            </tr>
        </table>
        <table class="table-responsive" style="background-color:gainsboro;width: 100%;border:inset;">
            <tr>
                <td>
                    @Html.LabelFor(model => model.Lat, "Enlem", htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @*@Html.Kendo().NumericTextBoxFor(model => model.Lat).Step(0.01m).Format("00.000000").Decimals(6)*@
                    @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lat, "Örneğin 36.590587", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Lon, "Boylam", htmlAttributes: new { @class = "control-label col-md-2" })</td>
                <td>
                    @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lon, "Örneğin 36.163656", new { @class = "text-danger" })

                    <input id="btnYardim" type="button" value="?" title="qwdafda" />
                    @(Html.Kendo().Tooltip()
                    .For("#btnYardim")
                   .Position(TooltipPosition.Top)
                   .Width(300)
                   .ShowOn(TooltipShowOnEvent.Click)
                   .Content("Help Text"))





                    <a href='javascript:getView();'>Harita</a>
                    <script type="text/javascript">
    function getView() {
        var Latt = $("#Lat").val();
        var Lonn = $("#Lon").val();
        //alert(Latt + '-' + Lonn);

                            //$('#divResult').load("@Html.Raw(Url.Action("GoogleMap", "Partial"))?Lat=" + Latt + "&Lon=" + Lonn);
                            $('#divResult').load("@Html.Raw(Url.Action("GoogleMap", "Partial"))?Lat=" + Latt + "&Lon=" + Lonn);
                        }
                    </script>
                    <div id='divResult'>
                    </div>

                    
                    
                    
                    @*<div id="myPartialView">
                        @Ajax.ActionLink("Merhaba", "MyPartialView",
                        new AjaxOptions
                        {
                            UpdateTargetId = "myPartialView",
                            InsertionMode = InsertionMode.Replace,
                            HttpMethod = "Get"
                        })
                    </div>*@




                    @*<div id="resultDiv">
                    @Ajax.ActionLink("This is an Ajax link", "GoogleMap", "Ilan", 
                    new AjaxOptions
                    {
                        Confirm = "Are you sure?",
                        HttpMethod = "Get",
                        UpdateTargetId = "resultDiv",
                        InsertionMode = InsertionMode.Replace
                    })

                    </div>*@

    </td>
                </tr>
            </table>
            <br /><br />



            <div class="form-group">
                @Html.LabelFor(model => model.IlanBasligi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IlanBasligi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IlanBasligi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.AnasayfadaGoster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AnasayfadaGoster)
                    @Html.ValidationMessageFor(model => model.AnasayfadaGoster, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Deleted)
                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IlanSahibi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanSahibi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanSahibi, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Fiyati, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fiyati, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fiyati, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lon, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.IlanResimleri, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IlanResimleri, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IlanResimleri, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.PostaKodu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostaKodu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostaKodu, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.IlanTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IlanTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IlanTarihi, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.GoruntulenmeSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GoruntulenmeSayisi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GoruntulenmeSayisi, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.AltKategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AltKategoriId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AltKategoriId, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

    @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }

Views/Ilan/GoogleMap.cshtml
<div class="experienceRestrictedText">
    <script src="//maps.google.com/maps/api/js?sensor=false&callback=initialize" type="text/javascript"></script>
    <script type="text/javascript">

        function initialize() {
            var Lat = '@ViewBag.Lat';
            var Lon = '@ViewBag.Lon';
            alert(Lat + ',' + Lon);
            //var myLatlng = new google.maps.LatLng(36.590587, 36.163656);
            var myLatlng = new google.maps.LatLng(Lat, Lon);
            var mapOptions = {
                zoom: 15,
                center: myLatlng
            }
            var map = new google.maps.Map(document.getElementById('map'), mapOptions);

            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: 'Hello World!'
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <div class="map" id="map" style="width:400px; height:400px;"></div>
</div>

Views/Ilan/MyPartialView.cshtml
@{
    Layout = null;
}

@*<!DOCTYPE html>

<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div>
                merhaba              
        </div>
    </body>
</html>*@
<div>
    merhaba
</div>

Views/Ilan/motoE.cshtml
@{
    ViewBag.Title = "motoE";
}

<h2>motoE</h2>






@(Html.Kendo().TabStrip()
          .Name("motoTabStrip")
        //.SelectedIndex(0)
                  .Animation(animation => animation.Open(open => open.Fade(FadeDirection.In)))
        //.Events(events => events
        //    .ContentLoad("onContentLoad")
        //    .Error("onError")
        //)
                    .Items(items => items.Add().Text("İlan Bilgisi").LoadContentFrom("Edit", "Ilan", new { id = ViewBag.IlanId }))
                    .Items(items => items.Add().Text("İlan Ayrıntıları").LoadContentFrom("Edit", "Motosiklet", new { id = ViewBag.MotosikletId }))

                    .SelectedIndex(ViewBag.index)

)